#!/usr/bin/env bash
# 自动部署脚本 - 推送到 GitHub Pages

set -euo pipefail

DEMO_NAME="${1:-demo}"
DEMO_DIR="$HOME/.openclaw/workspace/demos/$DEMO_NAME"

echo "🚀 部署 $DEMO_NAME 到 GitHub Pages..."

cd "$HOME/.openclaw/workspace/demos"

# 构建 gh-pages 分支
if ! git ls-remote --heads origin gh-pages | grep -q 'refs/heads/gh-pages'; then
    echo "创建 gh-pages 分支..."
    git checkout --orphan gh-pages
    git reset --hard
    echo "<h1>OpenClaw Demos</h1><p>Deploying...</p>" > index.html
    git add index.html
    git commit -m "Initial gh-pages"
    git push -u origin gh-pages
    git checkout main
fi

# 复制 demo 到 gh-pages
echo "同步到 gh-pages 分支..."
git checkout gh-pages

# 创建 demo 目录
mkdir -p "$DEMO_NAME"
cp -r "$DEMO_DIR"/* "$DEMO_NAME/" 2>/dev/null || true

# 更新主页面
cat > index.html << EOF
<!DOCTYPE html>
<html>
<head>
    <title>OpenClaw Demos</title>
    <meta charset="utf-8">
    <style>
        body { font-family: system-ui; max-width: 800px; margin: 50px auto; padding: 20px; }
        h1 { color: #333; }
        .demo { border: 1px solid #ddd; padding: 20px; margin: 10px 0; border-radius: 8px; }
        .demo a { color: #0066cc; text-decoration: none; }
        .demo a:hover { text-decoration: underline; }
    </style>
</head>
<body>
    <h1>🚀 OpenClaw Demos</h1>
    <p>AI 自动生成的演示项目</p>
    <div class="demo">
        <h2><a href="$DEMO_NAME/">$DEMO_NAME</a></h2>
        <p>Generated by Yuan (OpenClaw AI)</p>
    </div>
</body>
</html>
EOF

git add -A
git commit -m "Deploy $DEMO_NAME" || echo "无变更"
git push origin gh-pages

# 返回 main 分支
git checkout main

echo "✅ 部署完成！"
echo "🌐 访问：https://dota2mugen.github.io/openclaw-demos/$DEMO_NAME/"
